version: "3.8"

services: 
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:9000 -t ./
    ports:
      - "9000:9000"